### ISSUE TITLE
Error for non-hunter classes

### ISSUE THREAD

**Issue by Road-block** [Aviana/YaHT#1]
I forgot to disable the addon on a non-hunter class so this error happened.
`YaHT\defaults.lua:1: attempt to index global 'YaHT' (a nil value)  
YaHT\defaults.lua:1: in main chunk`

Reason is that the class check in [YaHT.lua:2](https://github.com/Aviana/YaHT/blob/e4144de731e6cfb7a50c224db9d5aa9e1377ee10/YaHT.lua#L2) returns before the YaHT object is initialized, so defaults.lua errors when trying to reference `YaHT.L`.

A number of ways to fix it:
- moving the class check after object init, to [line:17](https://github.com/Aviana/YaHT/blob/e4144de731e6cfb7a50c224db9d5aa9e1377ee10/YaHT.lua#L17) for example.
- a similar check of `if not YaHT then return end` in the defaults file etc.

**Comment by Aviana** [comment]
Fixed.
