### ISSUE TITLE
Can't see/configure Addon?

### ISSUE THREAD

**Issue by hesketh7085** [Aviana/YaHT#14]
Hi,

Your Code page says to download the latest release "-2.1" but the instructions still say "remove -master from the folder name" - this needs updating as it took me 30 minutes (new user) to figure out I needed to remove "-2.1"

Since doing that, "YaHT" appears in my in-game Addon list but not in my Addon Interface Options, and /YaHT has no effect. Please help!

**Comment by Kh4zy** [comment]
I got the same issue. Not really sure wich version I should use, but I have tried the 2.1 and 2.0 beta for now and currently, the addon is not working

**Comment by hesketh7085** [comment]
> I got the same issue. Not really sure wich version I should use, but I have tried the 2.1 and 2.0 beta for now and currently, the addon is not working

Thanks for the reply. I've also tried the 'Download & Clone' version (as told NOT to do) because that relates to the "-master" version in the outdated instructions... but same issue. So, it's in-game, but not available...

**Comment by Kh4zy** [comment]
> > I got the same issue. Not really sure wich version I should use, but I have tried the 2.1 and 2.0 beta for now and currently, the addon is not working
> 
> Thanks for the reply. I've also tried the 'Download & Clone' version (as told NOT to do) because that relates to the "-master" version in the outdated instructions... but same issue. So, it's in-game, but not available...

I cant see the addon ingame. It will load fine in the addon viewer, but I dont see anything ingame, hmm

**Comment by hesketh7085** [comment]
Yeah that's what I mean. I can see it in the Addons list, but not in the Interface Options list for Addons

**Comment by Aviana** [comment]
Forgot to upload the actual packaged release to the releases page.
