### ISSUE TITLE
Bar Constantly Changing Sizes, Even When Not In Combat

### ISSUE THREAD

**Issue by tylerku** [Aviana/YaHT#15]
Hello! So I just installed this addon on my mac. It appeared to install fine but when I am playing, the bar constantly fills up to full, turns red, and then immediately empties. It does this when I am not in combat, and taking shots while I am in combat doesn't seem to change the pattern of it filling up and shrinking itself. If this is just user error then awesome, but it seems something is  up.

**Comment by MarkusNemesis** [comment]
I have the same issue. Not sure what use it is, but I only use this for an autoshot timer, so if this is intended functionality, can we have a checkbox to disable it?

**Comment by Aviana** [comment]
Thats the demo mode when its not locked into place.
