### ISSUE TITLE
/cast Auto Shot cannot be used when addon is enabled

### ISSUE THREAD

**Issue by MarkusNemesis** [Aviana/YaHT#16]
When this addon is enabled, you cannot use `/cast Auto Shot` in a macro. It simply does nothing.

**Comment by stako** [comment]
I'm using `/cast !auto shot` with `/startattack` right after and it's working just fine for me

**Comment by MarkusNemesis** [comment]
Odd. I cannot reproduce it now.. It happened non stop all yesterday, until I unloaded YaHT and it worked again.

I verified by re-enabling YaHT and the issue restarted... But today? Not reproducible... Whaaat?
