### ISSUE TITLE
Classic errors

### ISSUE THREAD

**Issue by Jakobud** [Aviana/YaHT#17]
Thanks for the simple but great addon. A few errors I'm getting in Classic:

```
2x Couldn't open YaHT\libs\LibSharedMedia-3.0-8020002\lib.xml
```

```
2x Couldn't open YaHT\libs\AceDB-3.0-27\AceDB-3.0.xml
```

```
2x Couldn't open YaHT\libs\AceDBOptions-3.0-15\AceDBOptions-3.0.xml
```

```
2x Couldn't open YaHT\libs\AceGUI-3.0-39\AceGUI-3.0.xml
```

```
2x Couldn't open YaHT\libs\AceGUI-3.0-39-SharedMediaWidgets\widget.xml
```

```
2x Couldn't open YaHT\libs\AceConfig-3.0-3\AceConfig-3.0.xml
```

```
4x Error loading YaHT\libs\LibStub\LibStub.lua
```

```
4x Couldn't open YaHT\libs\CallbackHandler-1.0-7\CallbackHandler-1.0.xml
```

The addon still appears to be working just fine though, even with these errors.

**Comment by HristoYonkov** [comment]
wtf i cant even see how to use it ...

**Comment by stako** [comment]
The releases on GitHub are missing the Ace3 dependencies, which means you'll either get errors or the addon won't load at all. The version on Curse has the dependencies included - better to download from there.

**Comment by Aviana** [comment]
> 
> 
> The releases on GitHub are missing the Ace3 dependencies, which means you'll either get errors or the addon won't load at all. The version on Curse has the dependencies included - better to download from there.
