### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by fgsfdss** [Aviana/YaHT#2]
Cruzix said to post here instead of Elysium forums, so I'll repost here.

> Nice addon. A few suggestions:
> 
> - Make the tiny black border around the bar texture optional (so that we can have a perfect white/red bar)
> 
> - Customizable Tranq message
> 
> - Announce Tranq only once (Tank Buddy can do this for Last Stand / Shield Wall, you could refer to its code)
> 
> - Announce unsuccessful Tranqs (like Tank Buddy's taunt resist) when it misses or when mob is immune
>

**Comment by ghost** [comment]
> - Announce Tranq only once (Tank Buddy can do this for Last Stand / Shield Wall, you could refer to its code)
> - Announce unsuccessful Tranqs (like Tank Buddy's taunt resist) when it misses or when mob is immune

ZHunterMod already has these features, including localization for english, german and french clients. Could potentially save a lot of work.

**Comment by Aviana** [comment]
Implemented both tranq suggestions. The tiny black border is actually the background which is always a bit bigger than a frame that gets anchored to it. "Fixing" this would be a lot of effort for something i don't see as an issue but rather like.
