### ISSUE TITLE
2.11 Beta Error

### ISSUE THREAD

**Issue by Kh4zy** [Aviana/YaHT#22]
The timer is active all the time and is just moving and not in sync with the auto attack. Seems like its just a floating bar that does an animation.

**Comment by Kh4zy** [comment]
Videoes of the bug
https://plays.tv/video/5d6e24d38c28cb5cea/bug
https://plays.tv/video/5d6e251fc3eeeee80c/bug

**Comment by Aviana** [comment]
Duplicate of #15
