### ISSUE TITLE
Multi shot/aimed shot blizzard bar option

### ISSUE THREAD

**Issue by Sneakyrhino1** [Aviana/YaHT#24]
https://gyazo.com/8d962848e5366f8216c15f5bfe04b3ac

it currently shows any hunter using aimed shot/multishot as my own bar/overwrites my bar, i have tried every version and disabled/removed/renamed my wtf and still same issue

**Comment by Sneakyrhino1** [comment]
Quick update: if rapid fire is active the bar does not take into account the shortened cast time.

does not work with aspect of the hawk buff "quick shots" either.

**Comment by karyzan** [comment]
> Quick update: if rapid fire is active the bar does not take into account the shortened cast time.
> 
> does not work with aspect of the hawk buff "quick shots" either.

It doesnt work with ClassicShots addon either. I think it has to be coded manually with both buffs, or all haste buffs. If he adds the Rapid Fire, he needs to add the Hawk buff and then both buffs combined aswell.

**Comment by Aviana** [comment]
I know that haste and aimed shot are not working but i need to level my hunter to at least level 21 for testing (aimed shot + imp hawk). And i currently don't have the time to do so. Thats why development on this addon is slow.

**Comment by karyzan** [comment]
Is there any way we could help with that? Is it possible to take the info from wow head? If you want, you could add me on discord karYzan#2081 and I could test it for you as many times as you want! I'm almost always online. Thanks again for this addon by the way

**Comment by Aviana** [comment]
Should be fixed.
See #32 and #43
