### ISSUE TITLE
Aimed Shot not working

### ISSUE THREAD

**Issue by karyzan** [Aviana/YaHT#26]
Multi Shot is working but not aimed shot

**Comment by Sneakyrhino1** [comment]
+

**Comment by aduth** [comment]
Full error for me:

```
Date: 2019-09-09 01:02:45
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\YaHT\YaHT.lua line 280:
   attempt to perform arithmetic on local 'castTime' (a nil value)
Debug:
   YaHT\YaHT.lua:280: ?()
   YaHT\YaHT.lua:399:
      YaHT\YaHT.lua:394
```

May have been introduced with #25 (cc @Pat-). In my testing, `spellID` is returning `0` from `CombatLogGetCurrentEventInfo` (not sure why), so `castTime` on the next line is assigned as `nil`.

Possible workaround / fix: At line 228 in YaHT.lua, change `spellID` to `name`.
