### ISSUE TITLE
LUA Error when taking environmental damage

### ISSUE THREAD

**Issue by Peetytwist** [Aviana/YaHT#27]
Date: 2019-09-09 11:20:29
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\YaHT\YaHT.lua line 237:
   attempt to perform arithmetic on field 'maxValue' (a nil value)
Debug:
   YaHT\YaHT.lua:237: ?()
   YaHT\YaHT.lua:400:
      YaHT\YaHT.lua:395
Locals:
self = <table> {
 LoadDefaults = <function> defined @Interface\AddOns\YaHT\defaults.lua:3
 GetMedia = <function> defined @Interface\AddOns\YaHT\YaHT.lua:127
 OnInitialize = <function> defined @Interface\AddOns\YaHT\YaHT.lua:77
 Print = <function> defined @Interface\AddOns\YaHT\YaHT.lua:374
 db = <table> {
 }
 L = <table> {
 }
 STOP_AUTOREPEAT_SPELL = <function> defined @Interface\AddOns\YaHT\YaHT.lua:340
 ApplySettings = <function> defined @Interface\AddOns\YaHT\YaHT.lua:137
 COMBAT_LOG_EVENT_UNFILTERED = <function> defined @Interface\AddOns\YaHT\YaHT.lua:226
 MediaRegistered = <function> defined @Interface\AddOns\YaHT\YaHT.lua:119
 defaults = <table> {
 }
 UNIT_SPELLCAST_INTERRUPTED = <function> defined @Interface\AddOns\YaHT\YaHT.lua:303
 mainFrame = YaHTMainFrame {
 }
 CreateConfig = <function> defined @Interface\AddOns\YaHT\options.lua:11
 UNIT_RANGEDDAMAGE = <function> defined @Interface\AddOns\YaHT\YaHT.lua:370
 version = 2120
 START_AUTOREPEAT_SPELL = <function> defined @Interface\AddOns\YaHT\YaHT.lua:322
 ProfilesChanged = <function> defined @Interface\AddOns\YaHT\YaHT.lua:93
 UNIT_SPELLCAST_SUCCEEDED = <function> defined @Interface\AddOns\YaHT\YaHT.lua:348
 Load = <function> defined @Interface\AddOns\YaHT\YaHT.lua:196
 ProfileReset = <function> defined @Interface\AddOns\YaHT\YaHT.lua:106
}
_ = 1568020829.259000
event = "ENVIRONMENTAL_DAMAGE"
_ = true
casterID = ""
_ = nil
_ = -2147483648
_ = -2147483648
targetID = "Player-4477-0144CACE"
targetName = "Rîco"
_ = 1297
_ = 0
spellID = "Falling"
name = 685
_ = 0
extra_spell_id = 1
_ = nil
_ = nil
resisted = nil
blocked = false
absorbed = false
_ = nil
rank = nil
icon = nil
castTime = nil
icon = nil
castTime = nil
(*temporary) = CastingBarFrame {
 0 = <userdata>
 fadeOut = true
 showTradeSkills = true
 holdTime = 0
 Border = <unnamed> {
 }
 Flash = <unnamed> {
 }
 showCastbar = true
 Icon = <unnamed> {
 }
 startChannelColor = <table> {
 }
 finishedCastColor = <table> {
 }
 nonInterruptibleColor = <table> {
 }
 flash = true
 Text = <unnamed> {
 }
 unit = "player"
 showShield = false
 BorderShield = <unnamed> {
 }
 Spark = <unnamed> {
 }
 startCastColor = <table> {
 }
 flashColorSameAsStart = true
 finishedColorSameAsStart = true
 failedCastColor = <table> {
 }
}
(*temporary) = nil
(*temporary) = 0
(*temporary) = 0
(*temporary) = 1
(*temporary) = 0
(*temporary) = "attempt to perform arithmetic on field 'maxValue' (a nil value)"
AimedShot = "Gezielter Schuss"
AimedDelay = 1
MultiShot = "Mehrfachschuss"

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AtlasLootClassic, vv1.1.9-beta
  AucAdvanced, v8.2.6385 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6368 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v8.2.9
  BeanCounter, v8.2.6381 (SwimmingSeadragon)
  ClassicCastbars, vv1.0.4
  ClassicCastbarsOptions, v
  ClassicCodex, v1.2.1
  ClassicThreatMeter, v1.06
  ClassTrainerPlus, v0.5-beta
  DBMCore, v1.13.7
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Enchantrix, v8.2.6392 (SwimmingSeadragon)
  GatherLite, v1.2.13-classic
  Informant, v8.2.6374 (SwimmingSeadragon)
  LeatrixMaps, v1.13.28
  LeatrixPlus, v1.13.27
  LevelWatch, v0.1
  NeatPlates, v1.13.2.14-Classic
  NeatPlatesAlvara, v5a
  NeatPlatesBlizzardPlates, v1.5
  NeatPlatesClassicPlates, v
  NeatPlatesGraphite, v
  NeatPlatesGrey, v
  NeatPlatesNeon, v
  NeatPlatesQuatre, v
  NeatPlatesRenaitre, vv7.0.3
  NeatPlatesRoth, v
  NeatPlatesSimple, v7.3.0
  NeatPlatesSlimHorizontal, v2.2
  NeatPlatesSlimVertical, v2.2
  NeatPlatesHub, v
  NeatPlatesWidgets, v
  OmniCC, v8.1.1
  QuestXP, v0.2
  Recount, vv1.13.2b
  SexyMap, vv3-classic
  ShadowedUnitFrames, vv4.2-Classic-Beta6
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  SUF, v@project-version@
  TitanClassic, v1.0.5.11302
  TitanClassicAmmo, v1.0.5.11302
  TitanClassicBag, v1.0.5.11302
  TitanClassicClock, v1.0.5.11302
  TitanClassicGold, v1.0.5.11302
  TitanClassicLocation, v1.0.5.11302
  TitanClassicLootType, v1.0.5.11302
  TitanClassicPerformance, v1.0.5.11302
  TitanClassicRepair, v1.0.5.11302
  TitanClassicVolume, v1.0.5.11302
  TitanClassicXP, v1.0.5.11302
  TomCats, v0.0.2
  WhatsTraining, v1.7.1
  YaHT, v
  BlizRuntimeLib_deDE v1.13.2.11302 <none>
  (ck=7fe)

**Comment by aduth** [comment]
I think it's related to #25 (232cd3924b1ce95697225acc445f00a38f6464ba).

Reverting back to the original for lines 232-235 resolves the error for me:

_Before:_

```lua
			if name == AimedShot then
            AimedDelay = 1
            castTime = 3000
        else
```

_After:_

```lua
			if CastingBarFrame.Text:GetText() == AimedShot then
```
