### ISSUE TITLE
amishot cast bar on AzeriteUI_Classic or other UI plugin not show

### ISSUE THREAD

**Issue by JSZMonkey** [Aviana/YaHT#35]
amishot cast bar on AzeriteUI_Classic or other UI plugin not show

**Comment by Goldpaw** [comment]
AzeriteUI doesn't use the default blizzard cast bars, nor offer any API for others to plug into, so I would say it's not in the scope of this addon nor its responsiblity to provide any support for AzeriteUI, or any other custom UI.

**Comment by Slivo-fr** [comment]
I'm unable to get any castbar addon to catch the YAHT casts too :/

**Comment by Aviana** [comment]
YaHT does not "support" any other addons. Since they should be actively maintained its up to their maintainers to implement Aimed Shot castbars.

**Comment by Slivo-fr** [comment]
Wasn't this working on 1.12 ? :o
Maybe my castbar addon was implementing it, gonna check

**Comment by Aviana** [comment]
Yes it was in the 1.12 version because there weren't maintainers for the castbar addons.

**Comment by Slivo-fr** [comment]
Understood, I'm gonna push some feature request on said addons then.
Is there a doc I can point them to ?

**Comment by Aviana** [comment]
They can look at https://github.com/rgd87/LibClassicCasterino for "inspiration".

**Comment by Slivo-fr** [comment]
Great ! Thanks for your work btw, if you need some testing I'll be happy to give a hand
