### ISSUE TITLE
Tranq shot announce does not work.

### ISSUE THREAD

**Issue by Dulahey** [Aviana/YaHT#36]
Tested two different weeks and it didn't work either time.  Both the announcement and resist.

**Comment by Slivo-fr** [comment]
It looks like I have the same issue on my side, french client if that matter

**Comment by Slivo-fr** [comment]
I searched a bit about this, it looks like blizzard is always returning a 0 for `spellID` on classic .
You can however get the spell name I believe. Maybe you could add a fallback using name ?
