### ISSUE TITLE
Improve AimedShot/Multi-shot Cast bar capability/visuals

### ISSUE THREAD

**Issue by Hashmire** [Aviana/YaHT#37]
Not sure if this is something that YAHT is able to do, but having these events be caught by popular castbar addons such as Quartz would be great. 

If not able to do that, perhaps just having the YAHT casts for these be a bit more movable/customizable so it can match the other YAHT indicator.

**Comment by Slivo-fr** [comment]
Would be great, unable to get cast bars on dominos and eCastingBar too

**Comment by Aviana** [comment]
See https://github.com/Aviana/YaHT/issues/35#issuecomment-553559560
