### ISSUE TITLE
InCombatSkipped

### ISSUE THREAD

**Issue by herbstduft** [Aviana/YaHT#39]
13x YaHT\YaHT-2120.nil.lua:237: attempt to perform arithmetic on field 'maxValue' (a nil value)
YaHT\YaHT-2120.nil.lua:237: in function `?'
YaHT\YaHT-2120.nil.lua:400: in function <YaHT\YaHT.lua:395>

Locals:
InCombatSkipped

**Comment by Aviana** [comment]
Pretty sure i fixed this. Have you tried updating?
