### ISSUE TITLE
A Suggestion

### ISSUE THREAD

**Issue by jackajack** [Aviana/YaHT#4]
Hello Rhena, YAHT is coded in a much better way than Rais, thank you for your hard work.

I have one suggestion:

**Static Mode**

This mode is designed for players who find bars distracting and would like to see less action on their screen.
It would show a static icon on the middle of the screen when it's time to shoot (When it's time to stand and wait and do nothing). When the arrow leaves your bow, icon disappears until the next time.

Instead of a YAHT mode, you could release it seperately if you like. 

Waiting to hear from you. Best regards.

**Comment by Aviana** [comment]
I don't like the idea.
