### ISSUE TITLE
Licencing and code usage

### ISSUE THREAD

**Issue by Slivo-fr** [Aviana/YaHT#41]
Hey !

I'm starting to write an addon aiming to help hunters with tranqshot rotation.
As I'm really new to addon, I used YaHT as a reference and inspiration for the base and announces part.
The addon should grow on his own way past a first basic release.

As our code is really similar and I found no licence there, I have to ask you if you are fine with this.

Repo at https://github.com/Slivo-fr/TranqRotate

Thanks for your time

**Comment by Aviana** [comment]
Added a license.

**Comment by Slivo-fr** [comment]
Thanks <3
