### ISSUE TITLE
Timer bars are popping up for other hunters in group / raid

### ISSUE THREAD

**Issue by lec7grs** [Aviana/YaHT#47]
Hi there

When using it in a raid it is basically showing other hunters aimed and multi shot timers over the top of my own, therefore I have no idea (other than by watching it fire and listening to the sounds) whose timer it is thus making it kind of unusable - any ideas?!

Cheers

**Comment by Aviana** [comment]
This has been fixed last year.
https://github.com/Aviana/YaHT/issues/32

**Comment by lec7grs** [comment]
Apologies - didnt spot that - however I only downloaded this last week.  If another hunter was using an older version would it affect me do you know? Thanks for the reply
