### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by Hanzemon** [Aviana/YaHT#48]
**Description**
YahT is not working, I get an error as I log in.

**Version Number**
Lastest lol. 2.14 beyta

**Steps to Reproduce**
 Provide all the steps necessary to reproduce the problem
1. download and install addon
2. execute the game
3. log in
4. read error message

**Expected Behavior**
 the addon works fine

**Actual Behavior**
 the addon is not responsive at all, it shows an error as i log in 

**Only ElvUI Enabled**
Yes, when elvui is the only addon enabled appart from yaht, it does not work either, it is showing the same error massage.

**Blizzard Issue?**
It doesnt work if yaht s the only addon either

**Error Log**
this is the error that I get with no other addons enabled
```
Interface/addons/yaHT/libs/LibStub/libstub.lua: attempt to index global`_G' (a nil value)
```
when I have elvui enabled it shows 20 errors
90% of them say a "directory/document.lua:##:" followed by unexpected symbol near `...'
the other 10% say (a nil value)

**Comment by Aviana** [comment]
If you are running this on the 1.12 client you need to download "1.2 Final"
