### ISSUE TITLE
TBC Pre Patch

### ISSUE THREAD

**Issue by Mitroden** [Aviana/YaHT#50]
Hey Aviana

Looks like this is just straight up not working/showing in the TBC pre-patch client. I have loaded the 2.14 version, but not even showing up under addons in-game. Not sure if there is something else I can try to do to help you with this report?

**Comment by Aviana** [comment]
This addon has not been tested/modified to work with TBC. Since i don't play a hunter at the moment it is also lower on my priority list.

**Comment by andrewmcnaughton** [comment]
Are you able to direct me in what changes need to be made to make it TBC compatible? No changes, just working. It's such a valuable addon, would be a shame to not have it available.

**Comment by andrewmcnaughton** [comment]
Made a temporary fix, but unable to open pull request. Removing lines 183 and 186 in YaHT.lua make the addon playable.

**Comment by Zyin055** [comment]
> Made a temporary fix, but unable to open pull request. Removing lines 183 and 186 in YaHT.lua make the addon playable.

I tried doing this and it still doesn't display at all. Are your lines the same as my lines?
183: --self.mainFrame:Show()
186: --self.mainFrame.texture:SetVertexColor(config.drawcolor.r,config.drawcolor.g,config.drawcolor.b)

**Comment by andrewmcnaughton** [comment]
The lines you're looking for are:
self.mainFrame.border:SetBackdrop(backdrop)
self.mainFrame.border:GetBackdropBorderColor(config.bordercolor.r, config.bordercolor.g, config.bordercolor.b)

But I think i was mistaken, while the addon displays, i dont think its functioning correctly.

**Comment by Aviana** [comment]
I made an official fix. Please try and report further issues.

**Comment by andrewmcnaughton** [comment]
Thanks mate!
