### ISSUE TITLE
Errors on load

### ISSUE THREAD

**Issue by SubbyDK** [Aviana/YaHT#51]
Hey.

I'm so happy that I found this addon here on GitHub, was sure it was dead.
Thanks. :)

I'm getting 8 errors everytime I load the game.
**Game version:** TBC

**Error 1:**
7x Couldn't open YaHT\libs\LibSharedMedia-3.0-8020003\lib.xml

**Error 2:**
7x Couldn't open YaHT\libs\AceDB-3.0-27\AceDB-3.0.xml

**Error 3:**
7x Couldn't open YaHT\libs\AceDBOptions-3.0-15\AceDBOptions-3.0.xml

**Error 4:**
7x Couldn't open YaHT\libs\AceGUI-3.0-41\AceGUI-3.0.xml

**Error 5:**
7x Couldn't open YaHT\libs\AceGUI-3.0-41-SharedMediaWidgets\widget.xml

**Error 6:**
7x Couldn't open YaHT\libs\AceConfig-3.0-3\AceConfig-3.0.xml

**Error 7:**
14x Error loading YaHT\libs\LibStub\LibStub.lua

**Error 8:**
13x Couldn't open YaHT\libs\CallbackHandler-1.0-7\CallbackHandler-1.0.xml

Is that something there can be fixed ?

**Comment by Aviana** [comment]
You mean like following the instructions and downloading from the actual [release](https://github.com/Aviana/YaHT/releases) page?

**Comment by SubbyDK** [comment]
Thanks. :)

I don't really know my way around GitHub and could apparently not find the release page.
_(Found where on the page it is now. :D )_

Thanks for the link to it and a great addon. :)
