### ISSUE TITLE
Strange skipping issue when grouped with other Hunters

### ISSUE THREAD

**Issue by Mitroden** [Aviana/YaHT#53]
Hi Aviana

I got the strangest issue last night in Slave Pens. I ran I think ten runs, and when I was grouped with a Hunter for 3-4 of them the bar focussed in a very strange way. Some packs it was ok, and some it would start skipping halfway through and others it was like that for the whole pull. What I mean by skipping is that instead of moving swiftly and smoothly, it would skip and jump around as if I was experiencing knockback. What I eventually boiled it down to was that the other Hunters autoshot was interfering with mine. If he was drinking I wouldn't get this skipping, but as soon as he stood up and started shooting it started. I also found if I got far away from him it would stop. And when he left the Dungeon and was replaced by a Warrior, it never skipped again for another 4 Slave Pens...

I did an AV the night before and whilst on Drek, the skipping was impossible to see the bar. I didn't check if I was grouped with a Hunter or if one was in the Raid group, but I didn't know what to look out for then.

I hope this points you in the right direction for a possible fix?

**Comment by Ankeen-A** [comment]
Yep I'm getting this too

**Comment by Mitroden** [comment]
Hi Aviana, not sure if you saw this. Any chance of a fix? Thanks in advance for the great addon.
