### ISSUE TITLE
Multi SHot/ AImed Shot bugged with Pfui

### ISSUE THREAD

**Issue by weedpuff420** [Aviana/YaHT#8]
Hello, Aviana

I'm glad to see you have just released a new version of Yaht. The only problem is that with Pfui... the multishot/ aim shot cast bar are bugged when pfui is turned on. What and How do I fix Yaht to function properly with my Pfui. I'm very interested in using this epic add on so it would be great if you can let me know what I can do to fix the problem. 

Lastly, I'm trying to find out where the delay option is on the mod so I can adjust the multi shot and aim shot timer as shown here.

https://www.youtube.com/watch?v=xgw5TDDWmTI&list=PLZm1l6JD54o8yhkbjCV1agvkORDFB86yJ&index=17&t=0s

**Comment by Aviana** [comment]
Pfui does its own castbars for aimed / multi shot and what you linked in the video is a modified version not made by me.
